CREATE TABLE bookmarks
(
  bookmark_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  bookmark_site TEXT NOT NULL,
  bookmark_link TEXT NOT NULL,
  bookmark_desc TEXT,
  bookmark_rating INTEGER DEFAULT 0 NOT NULL
);